### ISSUE TITLE
Bug: empty Java arrays become NULL values in R

### ISSUE THREAD

**Issue by kenahoo** [s-u/REngine#12]
Consider the following:

```
rengine.assign("x", new REXPDouble(new double[]{}));
rengine.parseAndEval("is.null(x)")
```

This returns a `TRUE` value, but it should be assigning a non-NULL empty numeric vector, as in R:

```
> x <- numeric()
> is.null(x)
[1] FALSE
```

**Comment by kenahoo** [comment]
I have a workaround for some simple cases:

    private void zeroSafeAssign(String name, REXP rexp)
            throws REngineException, REXPMismatchException {
        if (rexp instanceof REXPVector && rexp.length() == 0) {
            // Create a vector of length 1, then remove the element to get a vector of length 0
            REXP rexp2 = rexp instanceof REXPDouble ? new REXPDouble(4.2)
                       : rexp instanceof REXPLogical ? new REXPLogical(true)
                       : rexp instanceof REXPInteger ? new REXPInteger(42)
                       : rexp instanceof REXPString ? new REXPString("grumble")
                       : rexp instanceof REXPRaw ? new REXPRaw(new byte[] { 42 })
                       : null;

            if (rexp2 == null)
                throw new UnsupportedOperationException("Don't (yet) know how to assign a zero-length vector of type '" + rexp.getClass() + "'");

            rengine.assign(name, rexp2);
            rengine.parseAndEval("`" + name + "` <- `" + name + "`[0]");
            return;
        }
        rengine.assign(name, rexp);
    }

However, this doesn't help in cases where a nested structure may have a deep element which is a length-zero vector.

**Comment by kenahoo** [comment]
Hi @s-u - I wonder if you've had a chance to look at this and think about how it might be solved.

**Comment by manuelwaltschek** [comment]
Seems like this is also true for assigning REXPList with an empty RList as payload?

**Comment by manuelwaltschek** [comment]
`	@Test
	public void testAssignEmptyAndNonEmptyREXPList() throws RserveException {
		RServeTestSession session = new RServeTestSession(HOST, PORT);
		RList emptyList = new RList(new REXP[] {});
		testAssignList(session, emptyList);
		RList conentList = new RList(new REXP[] {new REXPString("Hello")});
		testAssignList(session, conentList);
	}

	private void testAssignList(RServeTestSession session, RList emptyList) throws RserveException {
		REXPList emptyREXPList = new REXPList(emptyList);
		session.assign("myList", emptyREXPList);
		REXPLogical result = (REXPLogical) session.eval("is.null(myList)");
		MyRServe.checkRServeException(result, rcon);
		boolean[] trues = result.isTRUE();
		for (boolean b : trues) {
			System.out.println(b);
		}
	}`

**Comment by kenahoo** [comment]
This bug only seems to affect JNI engines, not RServe.

**Comment by s-u** [comment]
Thanks, yes, this seems like a deliberate (but inconsistent) decision in JRI. I have filed it as https://github.com/s-u/rJava/issues/271 since it has to be dealt with upstream, REngine is innocent in this.
