### ISSUE TITLE
Getting list of files available on Rserve

### ISSUE THREAD

**Issue by hlms** [s-u/REngine#14]
Using [RConnection#openFile(String filepath)](https://github.com/s-u/REngine/blob/master/Rserve/RConnection.java#L321), a user can open a file on the Rserve for reading.

Is there a way get the list of all files available?

Need to browse through the files available. Then I can pick one file for reading.

**Comment by s-u** [comment]
`eval("Sys.glob('...')")` is probably your friend here. Don't forget you can use all facilities of R.

**Comment by hlms** [comment]
@s-u ,
Here is my use-case:

User should be provided with the list of files available on R. User would navigate through the directories, and would select one file. My java code would fetch the file.

As you said, I can use the following commands in eval():

- [list.files](https://stat.ethz.ch/R-manual/R-devel/library/base/html/list.files.html) to get list of files.
- [list.dirs](https://stat.ethz.ch/R-manual/R-devel/library/base/html/list.files.html) to get list of directories.

Will need to manipulate the output of this two commands to generate a single list. A wrapper java program can be written using these two commands so that user will be able to navigate through the files/directories.

It gets tricky when R instance is on a windows machine. Need to get the list of drives on the machine:
```
> system("cmd.exe /c wmic logicaldisk get name", intern = F)
Name  
C:    
D:    
```
Need to check the OS as following:
```
> .Platform$OS.type
[1] "windows"
```
So, the flow differs based on underlying OS. Is there a way to write my java program which is NOT dependent on the underlying OS of R instance?

Are there any REST APIs for listing files/directories? (This question is for R, and not for Rserve.)
