### ISSUE TITLE
How to serialize a  returned back r model?

### ISSUE THREAD

**Issue by reminia** [s-u/REngine#18]
such as. 

model = r.eval("auto.arima(ts)")

This returns a model of type REXPGenericVector,
and I want to ObjectOutputStream to save this model.
But the type cant be serialized. 

Is there way to serialize a model by java client ?
But not save to a file in R server side.

**Comment by s-u** [comment]
see `?serialize` in R

**Comment by reminia** [comment]
@s-u  Thanks for your quick reply.

Yeah, we can 
val model = r.eval("serialize(model, NULL)")

But the returned model cant be serialized in java client side.

For REXPGenericVector is not serializable.

**Comment by s-u** [comment]
But that's not a generic vector (aka list) - the result is a byte array (raw vector) so the serialization is `model.asBytes();`

**Comment by reminia** [comment]
Thanks for the tip. It works.
