### ISSUE TITLE
Assigning named character vector

### ISSUE THREAD

**Issue by manuelwaltschek** [s-u/REngine#22]
Hi there, 

I tried to assign a named character vector with REngine, but failed to do so. Can you please give me a quick example? This is one of the things that I tried:
```

	@Test
	public void testAssignNamedCharacterVector() throws RserveException, REXPMismatchException {
		RServeTestSession session = new RServeTestSession(HOST, PORT);
		String[] names = new String[] {"A","B","C"};
		Collection<REXPString> load = Arrays.asList(new REXPString(new String[] {"1", "2", "3"}));
		RList namedCharacterList = new RList(load, names);
		REXPList namedCharacterVector = new REXPList(namedCharacterList);
		String symbolName = "myNamedCharacter";
		REXP result = assignAndEval(session, namedCharacterVector, symbolName);
		String typeof = testTypeOf(session, symbolName);
		REXP returnedNames = session.eval("names(myNamedCharacter)");
		System.out.println(result);
		System.out.println(returnedNames);
		System.out.println(typeof);
	}
```

Output:

> 2019-01-28 11:29:57,587 DEBUG  [RServeTestSession1008925772] (main) Assigning value org.rosuda.REngine.REXPList@35047d03[1]{A=org.rosuda.REngine.REXPString@49b0b76[3]{"1","2","3"}} to variable name myNamedCharacter of type class org.rosuda.REngine.REXPList 
> 2019-01-28 11:29:57,651 DEBUG  [RServeTestSession1008925772] (main) Sending command 'myNamedCharacter' for evaluation 
> 2019-01-28 11:31:30,762 DEBUG  [RServeTestSession1008925772] (main) Sending command 'typeof(myNamedCharacter)' for evaluation 
> 2019-01-28 11:31:32,172 DEBUG  [RServeTestSession1008925772] (main) Sending command 'names(myNamedCharacter)' for evaluation 
> org.rosuda.REngine.REXPList@49d904ec[1]named
> org.rosuda.REngine.REXPString@4b5d6a01[1]
> pairlist

**Comment by manuelwaltschek** [comment]
This is another thing I tried with REXPGenericVector, which at least returns a character vector containing the names A,B,C but typeof(myNamedCharacter) returns "list", not "character"

```
@Test
	public void testAssignNamedCharacterVector() throws RserveException, REXPMismatchException {
		RServeTestSession session = new RServeTestSession(HOST, PORT);
		String[] names = new String[] {"A","B","C"};
		Collection<REXPString> load = Arrays.asList(new REXPString(new String[] {"1", "2", "3"}));
		RList namedCharacterList = new RList(load, names);
		REXPGenericVector namedCharacterVector = new REXPGenericVector(namedCharacterList);
		//REXPList namedCharacterVector = new REXPList(namedCharacterList);
		String symbolName = "myNamedCharacter";
		REXP result = assignAndEval(session, namedCharacterVector, symbolName);
		String typeof = testTypeOf(session, symbolName);
		REXP returnedNames = session.eval("names(myNamedCharacter)");
		System.out.println(result);
		System.out.println(returnedNames);
		System.out.println(typeof);
	}
```

**Comment by s-u** [comment]
Named character vector is just a character vector with the `"names"` attribute so

```java
String[] names = new String[] {"A","B","C"};
String[] values = new String[] {"1", "2", "3"};
REXPString s = new REXPString(values,
  new REXPList(new REXPString(names), "names"));
```
