### ISSUE TITLE
Error while processing eval output: SEXP (type 10) expected but found result type 103.

### ISSUE THREAD

**Issue by ifo1999** [s-u/REngine#23]
Hello, I'm using your library to link java and r.

I thank you for providing the library

I called the R script without error
After that when I access the result
I found the error message in the WAS log like below
(It happens sometimes, not every call)

Java code (Error occured at this line)
String stsMsg = rcon.eval("stsMsg").asString();

R code (function)
stsMsg <- "" #Success or fail msg
getPredVndrCost=function(){
stsMsg <<- "E001_xxxxxx"
stsMsg <<- "E002_yyyyyyyyyyyyyyyy."
stsMsg <<- "E003_ccccccccccc."
}

Error msg
org.rosuda.REngine.Rserve.RserveException: Error while processing eval output: SEXP (type 10) expected but found result type 103.

**Comment by s-u** [comment]
Not enough information to reproduce.
