### ISSUE TITLE
Rserve and REngine JDK

### ISSUE THREAD

**Issue by pvb05** [s-u/REngine#29]
Hi,

I see that Rserve 1.8-10 is compiled using JDK11 whereas REngine 1.8-10 is compiled using JDK6. Was there a specific reason for doing it?

thanks,
Pradeep V.B.

**Comment by s-u** [comment]
Can you elaborate what you mean by "complied with"? Rserve is C code, so there is no JDK involved (and there is no REngine version 1.8-10).

**Comment by PradeepBadiger** [comment]
REngine java library available in the download package (https://www.rforge.net/Rserve/snapshot/Rserve_1.8-10.tar.gz) is compiled using Java 1.6. Whereas Rserve java library in the same package is compiled using Java 11.

**Comment by s-u** [comment]
Ok, now I see - what you mean is that `inst/java/Rserve.jar` is compiled with Java 11 and `inst/java/REngine.jar` with Java 1.6. It seems that `JFLAGS` is ignored when compiling `Rserve.jar`. Should be now fixed in 184c4635. Thanks!

**Comment by pvb05** [comment]
Thanks for taking care of it.
