### ISSUE TITLE
Overflow getting long from R to java

### ISSUE THREAD

**Issue by NiceWeather** [s-u/REngine#8]
I try to get a long value from R to java.  Due to a missing method asLong() I tried as double and as BigInteger. Both ways do not work.  Perhaps, the problem is not located in your project, but if there is an error in R, presumably your project has to be adapted too.

    @Test
    public final void testWithDouble() throws Exception {
        REngine engine;
        engine = REngine.engineForClass("org.rosuda.REngine.JRI.JRIEngine");
        engine.parseAndEval("rm(list=ls(all=TRUE))");
        engine.assign("a", new int[] { 100000 });
        engine.parseAndEval("b <- a * a");
        REXP exp = engine.parseAndEval("b", null, true);
        double b = exp.asDouble();
        System.out.println(b); // prints -2.147483648E9
        Assert.assertEquals(1e10, b, 1.0);
    }

    @Test
    public final void testWithBigInteger() throws Exception {
        REngine engine;
        engine = REngine.engineForClass("org.rosuda.REngine.JRI.JRIEngine");
        engine.parseAndEval("rm(list=ls(all=TRUE))");
        engine.assign("a", new int[] { 100000 });
        engine.parseAndEval("b <- a * a");
        REXP exp = engine.parseAndEval("options(scipen=99); toString(b)", null, true);
        String b = exp.asString();
        System.out.println(b); // prints "NA"
        Assert.assertEquals("10000000000", b);
		// Now, this can be used to create a BigInteger and then the method longValue() helps.
    }

More details are written at http://stackoverflow.com/questions/35983826/getting-a-long-value-from-r-to-java.

**Comment by s-u** [comment]
Please consider reading the R documentation:

```
     If both arguments are of type integer, the type of the
     result of ‘/’ and ‘^’ is numeric and for the other operators it is
     integer (with overflow, which occurs at +/- (2^31 - 1), returned
     as ‘NA_integer_’ with a warning).
```

so the value of `b` is `NA_integer_`. This has nothing to do with REngine (other than that using `isNA` would have shown that those are `NA`s).
