### ISSUE TITLE
R parser: input incomplete

### ISSUE THREAD

**Issue by 214686604** [s-u/REngine#9]
Hi,
When I run below code and the console show RserveException named input incomplete. But I can do it in serve. Is there someplace I need to improve? Could I use sparkR in java?

                      RConnection c = new RConnection();
			REXP rn = c.eval("library(SparkR)");
			c.eval("sc<-sparkR.init()");
			c.eval("lines<-textFile(sc,\"README.md\"");

Many Thanks.

**Comment by Lvnszn** [comment]
Lack of a ) in c.eval("lines<-textFile(sc,\"README.md\"");
